// Dicionários da Home e do motor por idioma (pt, en, es)
// Regras: sem travessão longo, sem ponto-e-vírgula, sem clichês e com ritmo humano.

export const HOME_TEXTOS = {
  "pt": {
    "home_link_precos_planos": "/precos#planos",
    "home_link_precos": "/precos",
    "home_hero_h1": "Do modelo 3D à apresentação final sem trocar de programa.",
    "home_hero_apoio": "O Cora lê os materiais e a luz da sua cena no SketchUp ou no navegador. Você confere a leitura antes de gerar, e a imagem sai fiel ao que você projetou.",
    "home_hero_btn_criar": "Criar conta",
    "home_hero_btn_planos": "Ver planos",
    "home_passos_titulo": "O fluxo inteiro em três passos:",
    "home_passos_q0_tipo": "Passo 1 · Captura",
    "home_passos_q0_desc": "Viewport do SketchUp enquadrada com o modelo 3D e o recorte exato de proporção ativo",
    "home_passos_q1_tipo": "Passo 2 · Leitura",
    "home_passos_q1_desc": "Interface do Cora mapeando geometria, materiais aplicados e iluminação da cena antes de gerar",
    "home_passos_q2_tipo": "Passo 3 · Render & Refino",
    "home_passos_q2_desc": "Render finalizado com ferramentas de troca de clima, refino de detalhes e upscale em alta resolução",
    "home_passos_aria_lista": "Os três passos",
    "home_passos_tab0_titulo": "Modele e enquadre normalmente.",
    "home_passos_tab0_desc": "Continue no SketchUp exatamente como você já faz. O Cora marca na viewport o recorte exato que vai entrar na imagem, e você salva a cena.",
    "home_passos_tab1_titulo": "O Cora lê a cena.",
    "home_passos_tab1_desc": "Antes de gerar, a plataforma identifica os materiais e a luz que você aplicou no 3D. Você confere o que ela mapeou, ajusta o que precisar e aprova.",
    "home_passos_tab2_titulo": "Renderize e refine no mesmo lugar.",
    "home_passos_tab2_desc": "A imagem nasce fiel à geometria. A partir daí você edita detalhes, muda o clima, cria vistas 360° e amplia a resolução sem abrir outro programa.",
    "home_passos_nota_forte": "Não usa SketchUp?",
    "home_passos_nota_texto": "Na versão web o passo 1 é subir uma imagem. O resto é igual.",
    "home_demo_titulo": "Do print ao render, sem perder o projeto.",
    "home_demo_p1_alt_depois": "A mesma cena renderizada no Cora: estar e jantar com laje de concreto aparente, mesa de mármore verde, painel de madeira e o jardim de inverno atrás do vidro",
    "home_demo_p1_alt_antes": "A mesma cena crua na viewport do SketchUp: geometria e enquadramento idênticos, sem iluminação configurada e com os materiais ainda planos",
    "home_demo_p1_aria_alca": "Arraste para comparar o print do SketchUp com o render do Cora",
    "home_demo_p1_titulo": "O ponto de partida",
    "home_demo_p1_desc": "A cena crua do SketchUp, sem material tratado e sem luz. Arraste para comparar com o render gerado pelo Cora.",
    "home_demo_p2_aria_lista": "Câmeras do Batch",
    "home_demo_p2_cam1": "Câmera 01",
    "home_demo_p2_cam2": "Câmera 02",
    "home_demo_p2_cam3": "Câmera 03",
    "home_demo_p2_cam4": "Câmera 04",
    "home_demo_p2_cam5": "Câmera 05",
    "home_demo_p2_alt0": "Jantar e cozinha em enfilade sob o mesmo teto ripado, com banquetas na bancada e morador em circulação",
    "home_demo_p2_alt1": "Estar com parede de concreto aparente, poltrona amarela, quadro colorido e o jardim tropical atrás do vidro",
    "home_demo_p2_alt2": "Mesa de jantar com cadeiras verdes e luminária de discos, escada e cozinha ao fundo",
    "home_demo_p2_alt3": "Estar voltado para o jardim tropical através do vidro, com televisor embutido na parede de concreto",
    "home_demo_p2_alt4": "Estar com painel de madeira, televisor, duas poltronas amarelas e a escada ao fundo",
    "home_demo_p2_toque_ant": "Câmera anterior",
    "home_demo_p2_toque_prox": "Próxima câmera",
    "home_demo_p2_titulo": "As cinco vistas",
    "home_demo_p2_desc": "Mesmo ambiente, cinco câmeras. A madeira, o piso e a luz continuam os mesmos em todas as imagens.",
    "home_demo_p3_tipo": "Vídeo Looping / GIF",
    "home_demo_p3_desc_rotulo": "Gravação da tela demonstrando o cálculo do reflexo real do espelho no Cora Render",
    "home_demo_p3_titulo": "O espelho",
    "home_demo_p3_desc": "O reflexo mostra o ambiente que existe no modelo, não um inventado.",
    "home_demo_p4_alt_depois": "A mesma planta humanizada pelo Cora: pisos com paginação real, mobiliário, vegetação e sombras calculadas pela luz solar",
    "home_demo_p4_alt_antes": "Planta técnica em linhas 2D exportada do CAD, mesmo recorte e mesma escala",
    "home_demo_p4_aria_alca": "Arraste para comparar a planta técnica e a planta humanizada",
    "home_demo_p4_titulo": "A planta",
    "home_demo_p4_desc": "O desenho técnico e a planta humanizada gerada a partir dele.",
    "home_demo_p5_aria_visor": "Visualizador 360 graus interativo. Arraste com o mouse ou toque para navegar pelo ambiente.",
    "home_demo_p5_titulo": "O 360°",
    "home_demo_p5_desc": "Arraste para percorrer o ambiente.",
    "home_ferramentas_titulo": "Uma única esteira de produção.",
    "home_ferramentas_apoio": "O Cora lê a cena, gera, corrige e finaliza, em camadas, até a imagem estar pronta para a apresentação.",
    "home_ferramentas_aria_filtros": "Filtrar ferramentas",
    "home_ferramentas_filtro_todas": "Todas",
    "home_ferramentas_filtro_imagem": "Imagem",
    "home_ferramentas_filtro_edicao": "Edição",
    "home_ferramentas_filtro_video": "Vídeo",
    "home_onde_titulo": "No SketchUp ou no navegador",
    "home_onde_frase_1": "Mesma conta, mesmos créditos, mesmo histórico.",
    "home_onde_frase_2": "O que muda é por onde você começa.",
    "home_onde_aria_switch": "Onde usar o Cora",
    "home_onde_tab_plugin": "Plugin para SketchUp",
    "home_onde_tab_web": "Versão web",
    "home_onde_plugin_titulo": "Plugin para SketchUp",
    "home_onde_plugin_p1": "Renderize direto da sua cena sem exportar arquivos. O plugin reconhece a geometria e os materiais aplicados, captura o enquadramento exato da viewport e calcula o reflexo real dos espelhos do projeto.",
    "home_onde_plugin_p2": "Inclui as ferramentas locais para organizar materiais e blocos, projetar texturas e otimizar o arquivo na sua máquina, com processamento veloz e sem consumir nenhum crédito da assinatura.",
    "home_onde_rotulo_plugin": "Plugin SketchUp",
    "home_onde_desc_plugin": "Captura da interface do plugin Cora aberta dentro do SketchUp com ferramentas de materiais, viewport e reflexos",
    "home_onde_web_titulo": "Versão web",
    "home_onde_web_p1": "Projetado para quem modela em Revit, Archicad e Promob, ou parte de fotos de obra e croquis conceituais. Basta fazer o upload de uma imagem base para iniciar o render e a esteira de edição.",
    "home_onde_web_p2": "Acesse o histórico e refine imagens de qualquer computador, tablet ou celular pelo navegador. O render 360° é a única ferramenta exclusiva do plugin, por depender do posicionamento da câmera 3D.",
    "home_onde_rotulo_web": "Versão Web",
    "home_onde_desc_web": "Captura da interface do Cora no navegador com upload de imagem (Revit, Archicad, Promob ou croqui) e esteira de edição",
    "home_autoria_titulo": "Criado por quem já faz isso todo dia",
    "home_autoria_bio_1": "Marilia Fischer é arquiteta, trabalha com ArchViz há 10 anos e fundou o 9barra7, estúdio de renderização que atende construtoras e escritórios de arquitetura.",
    "home_autoria_bio_2": "O Cora Render nasceu do fluxo de trabalho dela, são ferramentas que ela usa no estúdio e ensina no 9barra7 Academy.",
    "home_autoria_rotulo_alunos": "alunos em 12 países",
    "home_autoria_alt_foto": "Marilia Fischer, arquiteta, fundadora do 9barra7 e criadora do Cora Render",
    "home_autoria_citacao": "“A IA não conhece o seu cliente, nem a intenção do projeto, nem quais decisões de arquitetura são inegociáveis. Essa leitura continua sendo sua. O Cora acelera o resto.”",
    "home_autoria_papel": "Arquiteta, fundadora do 9barra7 e criadora do Cora Render.",
    "home_planos_titulo": "Uma assinatura única para todo o processo de imagem.",
    "home_planos_apoio": "Do primeiro render ao ajuste final de pós-produção em alta resolução. Todas as etapas reunidas numa única plataforma, dimensionada para o volume do seu escritório.",
    "home_planos_pitch_starter": "Pra começar.",
    "home_planos_por_mes": "/mês",
    "home_planos_creditos_mes": "créditos por mês",
    "home_planos_starter_aprox": "Aprox.",
    "home_planos_starter_img_em": "imagens em",
    "home_planos_assinar_starter": "Assinar Starter",
    "home_planos_selo_recomendado": "Recomendado",
    "home_planos_pitch_pro": "O dia a dia de quem entrega projeto.",
    "home_planos_pro_beneficio": "Libera animação, pós-produção e upscale 16K",
    "home_planos_assinar_pro": "Assinar Pro",
    "home_planos_pitch_studio": "Alto volume.",
    "home_planos_studio_beneficio": "Fila de processamento prioritária",
    "home_planos_assinar_studio": "Assinar Studio",
    "home_planos_equipe_chamada": "Está na dúvida? Teste 7 dias no Free. É pro escritório todo? Conheça o Cora Teams.",
    "home_planos_equipe_btn": "Ver planos e detalhes",
    "home_faq_titulo": "Perguntas frequentes",
    "home_faq_q1": "Preciso usar SketchUp?",
    "home_faq_r1": "Não. O plugin é a porta de entrada pra quem já modela no SketchUp, mas a versão web parte de qualquer imagem. Quem trabalha em Revit, Archicad, 3ds Max, Promob ou faz projetos manuais pode fazer o upload e começar pelo navegador. A conta, os créditos e o histórico são os mesmos nas duas versões.",
    "home_faq_q2": "O Cora substitui o V-Ray ou o Enscape?",
    "home_faq_r2": "Sim, essa é a proposta. O Cora foi criado para você não depender mais de renderizadores pesados e demorados. Em vez de passar horas configurando luz física, mapas de materiais e esperando o computador destravar, você gera imagens com qualidade de apresentação em poucos minutos, direto do seu arquivo.",
    "home_faq_q3": "O que são créditos?",
    "home_faq_r3_parte1": "Crédito é a unidade que a IA consome a cada geração. Cada plano vem com uma cota mensal. O Starter, por exemplo, entrega",
    "home_faq_r3_parte2": "créditos, cerca de",
    "home_faq_r3_parte3": "imagens em",
    "home_faq_r3_parte4": ". As ferramentas locais do plugin não usam IA e não consomem crédito.",
    "home_faq_q4": "Os créditos acumulam de um mês para o outro?",
    "home_faq_r4": "Não. Todo mês a sua cota volta cheia, na quantidade do seu plano. O que sobrou do mês anterior não soma com a cota nova. As recargas avulsas funcionam diferente: ficam guardadas por 6 meses e só entram quando os créditos do plano acabam.",
    "home_faq_q5": "A leitura de materiais consome créditos?",
    "home_faq_r5": "Sim. A leitura usa IA, então tem custo de geração. Mas você paga uma vez: toda leitura fica salva na aba Análises e pode ser reaproveitada em qualquer render futuro daquela cena, no plugin ou no navegador.",
    "home_faq_q6": "E se eu precisar de mais créditos no meio do mês?",
    "home_faq_r6": "Dá para comprar uma recarga a qualquer momento. Os pacotes avulsos ficam no painel da sua conta, entram na hora e não dependem da data da sua renovação. Eles só começam a ser consumidos depois que os créditos do plano acabam, e valem por 6 meses.",
    "home_faq_q7": "Como funcionam os 7 dias grátis?",
    "home_faq_r7": "Você cria a conta e tem 7 dias para conhecer a plataforma por dentro e usar todas as ferramentas locais do plugin, as que rodam na sua máquina: leitura e organização de materiais, Material ID, espelho e vidro, otimizar modelo e purge. A geração de imagem entra junto com o plano, porque é o plano que traz os créditos. No teste não pedimos cartão.",
    "home_faq_q8": "Preciso saber escrever prompt?",
    "home_faq_r8": "Não. Prompt malfeito é o que faz a IA errar, então esse trabalho não fica com você. Cada ferramenta do Cora tem um agente do 9barra7 que escreve o prompt técnico a partir da sua descrição em português normal. Você fala como falaria com um colega de escritório, e a parte técnica fica com ele.",
    "home_faq_q9": "Posso usar em mais de um computador?",
    "home_faq_r9": "Pode. Em qualquer plano, a versão web aceita até 3 dispositivos e o plugin até 2 computadores, com uso em um por vez. Você gerencia e remove dispositivos pelo painel da sua conta.",
    "home_faq_q10": "O Cora vem com biblioteca de materiais e blocos?",
    "home_faq_r10": "Não. Ele organiza e lê as bibliotecas que você já tem: materiais em .vrmat, o formato do V-Ray, e blocos em .skp. Se você já tem biblioteca de V-Ray, é só apontar a pasta e continuar usando, sem converter nada.",
    "home_faq_q11": "Preciso de internet para trabalhar?",
    "home_faq_r11": "Sim. A validação da conta e o processamento com IA acontecem na nuvem. Mas com o plugin aberto, as ferramentas locais de modelagem continuam funcionando mesmo se a conexão cair.",
    "home_faq_q12": "E se a imagem sair errada?",
    "home_faq_r12": "Acontece. A IA é probabilística, e a mesma cena pode gerar resultados diferentes. Por isso existe a aba Editar: em vez de renderizar tudo de novo, você corrige só a região que ficou errada e preserva o resto da imagem."
  },
  "en": {
    "home_link_precos_planos": "/en/precos#planos",
    "home_link_precos": "/en/precos",
    "home_hero_h1": "From 3D model to final presentation without switching software.",
    "home_hero_apoio": "Cora reads the materials and light in your scene, in SketchUp or in the browser. You check the reading before generating, and the image comes out true to what you designed.",
    "home_hero_btn_criar": "Create account",
    "home_hero_btn_planos": "See plans",
    "home_passos_titulo": "The whole workflow in three steps:",
    "home_passos_q0_tipo": "Step 1 · Capture",
    "home_passos_q0_desc": "SketchUp viewport framed with the 3D model and exact aspect ratio crop active",
    "home_passos_q1_tipo": "Step 2 · Reading",
    "home_passos_q1_desc": "Cora interface mapping geometry, applied materials, and scene lighting before generating",
    "home_passos_q2_tipo": "Step 3 · Render & Refine",
    "home_passos_q2_desc": "Finished render with mood change tools, detail refinement, and high-resolution upscale",
    "home_passos_aria_lista": "The three steps",
    "home_passos_tab0_titulo": "Model and frame as usual.",
    "home_passos_tab0_desc": "Continue in SketchUp exactly as you do. Cora marks the exact crop that will enter the image on the viewport, and you save the scene.",
    "home_passos_tab1_titulo": "Cora reads the scene.",
    "home_passos_tab1_desc": "Before generating, the platform identifies the materials and light you applied in 3D. You check what it mapped, adjust as needed, and approve.",
    "home_passos_tab2_titulo": "Render and refine in the same place.",
    "home_passos_tab2_desc": "The image is created true to geometry. From there you edit details, change the mood, create 360° views, and increase resolution without opening another program.",
    "home_passos_nota_forte": "Don't use SketchUp?",
    "home_passos_nota_texto": "In the web version, step 1 is uploading an image. The rest is the same.",
    "home_demo_titulo": "From viewport screenshot to render, without losing the project.",
    "home_demo_p1_alt_depois": "The same scene rendered in Cora: living and dining area with exposed concrete slab, green marble table, wood paneling, and the winter garden behind glass",
    "home_demo_p1_alt_antes": "The same raw scene in the SketchUp viewport: identical geometry and framing, without configured lighting and with flat materials",
    "home_demo_p1_aria_alca": "Drag to compare the SketchUp screenshot with the Cora render",
    "home_demo_p1_titulo": "The starting point",
    "home_demo_p1_desc": "The raw scene in SketchUp, without treated materials and without light. Drag to compare with the render generated by Cora.",
    "home_demo_p2_aria_lista": "Batch cameras",
    "home_demo_p2_cam1": "Camera 01",
    "home_demo_p2_cam2": "Camera 02",
    "home_demo_p2_cam3": "Camera 03",
    "home_demo_p2_cam4": "Camera 04",
    "home_demo_p2_cam5": "Camera 05",
    "home_demo_p2_alt0": "Dining and kitchen enfilade under the same slatted ceiling, with counter stools and person in circulation",
    "home_demo_p2_alt1": "Living room with exposed concrete wall, yellow armchair, colorful artwork, and tropical garden behind glass",
    "home_demo_p2_alt2": "Dining table with green chairs and disc pendant light, stairs, and kitchen in the background",
    "home_demo_p2_alt3": "Living room facing the tropical garden through glass, with television built into the concrete wall",
    "home_demo_p2_alt4": "Living room with wood paneling, television, two yellow armchairs, and stairs in the background",
    "home_demo_p2_toque_ant": "Previous camera",
    "home_demo_p2_toque_prox": "Next camera",
    "home_demo_p2_titulo": "The five views",
    "home_demo_p2_desc": "Same space, five cameras. The wood, flooring, and light remain the same in every image.",
    "home_demo_p3_tipo": "Looping Video / GIF",
    "home_demo_p3_desc_rotulo": "Screen recording showing real mirror reflection calculation in Cora Render",
    "home_demo_p3_titulo": "The mirror",
    "home_demo_p3_desc": "The reflection shows the actual environment in the model, not an invented one.",
    "home_demo_p4_alt_depois": "The same floor plan rendered by Cora: real floor patterns, furniture, vegetation, and sunlight calculated shadows",
    "home_demo_p4_alt_antes": "Technical 2D line floor plan exported from CAD, same crop and scale",
    "home_demo_p4_aria_alca": "Drag to compare the technical floor plan with the furnished plan",
    "home_demo_p4_titulo": "The floor plan",
    "home_demo_p4_desc": "The technical drawing and the furnished floor plan generated from it.",
    "home_demo_p5_aria_visor": "Interactive 360-degree viewer. Drag with mouse or touch to navigate the space.",
    "home_demo_p5_titulo": "The 360°",
    "home_demo_p5_desc": "Drag to explore the space.",
    "home_ferramentas_titulo": "A single production workflow.",
    "home_ferramentas_apoio": "Cora reads the scene, generates, edits, and finalizes, in layers, until the image is presentation ready.",
    "home_ferramentas_aria_filtros": "Filter tools",
    "home_ferramentas_filtro_todas": "All",
    "home_ferramentas_filtro_imagem": "Image",
    "home_ferramentas_filtro_edicao": "Editing",
    "home_ferramentas_filtro_video": "Video",
    "home_onde_titulo": "In SketchUp or in the browser",
    "home_onde_frase_1": "Same account, same credits, same history.",
    "home_onde_frase_2": "What changes is where you start.",
    "home_onde_aria_switch": "Where to use Cora",
    "home_onde_tab_plugin": "SketchUp plugin",
    "home_onde_tab_web": "Web version",
    "home_onde_plugin_titulo": "SketchUp plugin",
    "home_onde_plugin_p1": "Render directly from your scene without exporting files. The plugin identifies geometry and applied materials, captures the exact viewport framing, and calculates real mirror reflections.",
    "home_onde_plugin_p2": "Includes local tools to organize materials and components, project textures, and optimize files on your computer, with fast processing and zero subscription credit consumption.",
    "home_onde_rotulo_plugin": "SketchUp Plugin",
    "home_onde_desc_plugin": "Screenshot of the Cora plugin interface inside SketchUp with material tools, viewport, and reflections",
    "home_onde_web_titulo": "Web version",
    "home_onde_web_p1": "Designed for those modeling in Revit, Archicad, and Promob, or starting from site photos and conceptual sketches. Upload a base image to start rendering and editing.",
    "home_onde_web_p2": "Access history and refine images from any computer, tablet, or phone in the browser. 360° render is the only plugin-exclusive tool, as it relies on 3D camera positioning.",
    "home_onde_rotulo_web": "Web Version",
    "home_onde_desc_web": "Screenshot of the Cora browser interface with image upload (Revit, Archicad, Promob, or sketch) and editing workflow",
    "home_autoria_titulo": "Created by someone who does this every day",
    "home_autoria_bio_1": "Marilia Fischer is an architect with 10 years in ArchViz and founder of 9barra7, a rendering studio serving builders and architecture firms.",
    "home_autoria_bio_2": "Cora Render grew out of her daily workflow, built with tools she uses in the studio and teaches at 9barra7 Academy.",
    "home_autoria_rotulo_alunos": "students in 12 countries",
    "home_autoria_alt_foto": "Marilia Fischer, architect, founder of 9barra7 and creator of Cora Render",
    "home_autoria_citacao": "“AI does not know your client, the design intent, or which architecture decisions are non-negotiable. That judgment remains yours. Cora accelerates the rest.”",
    "home_autoria_papel": "Architect, founder of 9barra7 and creator of Cora Render.",
    "home_planos_titulo": "A single subscription for the entire image workflow.",
    "home_planos_apoio": "From the initial render to final high-resolution post-production. Every step in a single platform, sized for your studio volume.",
    "home_planos_pitch_starter": "To get started.",
    "home_planos_por_mes": "/month",
    "home_planos_creditos_mes": "credits per month",
    "home_planos_starter_aprox": "Approx.",
    "home_planos_starter_img_em": "images in",
    "home_planos_assinar_starter": "Subscribe Starter",
    "home_planos_selo_recomendado": "Recommended",
    "home_planos_pitch_pro": "Daily work for delivering projects.",
    "home_planos_pro_beneficio": "Unlocks animation, post-production, and 16K upscale",
    "home_planos_assinar_pro": "Subscribe Pro",
    "home_planos_pitch_studio": "High volume.",
    "home_planos_studio_beneficio": "Priority processing queue",
    "home_planos_assinar_studio": "Subscribe Studio",
    "home_planos_equipe_chamada": "Wondering if it fits? Try 7 days on Free. Need it for the whole studio? Discover Cora Teams.",
    "home_planos_equipe_btn": "See plans and details",
    "home_faq_titulo": "FAQ",
    "home_faq_q1": "Do I need to use SketchUp?",
    "home_faq_r1": "No. The plugin is the entry point for SketchUp users, but the web version starts from any image. If you work in Revit, Archicad, 3ds Max, Promob, or create hand sketches, upload your image and start in the browser. Account, credits, and history are shared across both versions.",
    "home_faq_q2": "Does Cora replace V-Ray or Enscape?",
    "home_faq_r2": "Yes, that is the goal. Cora was built so you no longer rely on heavy, slow renderers. Instead of spending hours setting up physical lights, material maps, and waiting on your machine, you generate presentation quality images in minutes, straight from your model.",
    "home_faq_q3": "What are credits?",
    "home_faq_r3_parte1": "Credits are the unit consumed by AI on each generation. Every plan includes a monthly quota. Starter, for example, includes",
    "home_faq_r3_parte2": "credits, about",
    "home_faq_r3_parte3": "images in",
    "home_faq_r3_parte4": ". Local plugin tools do not use AI and do not consume credits.",
    "home_faq_q4": "Do credits roll over from one month to the next?",
    "home_faq_r4": "No. Each month your quota refreshes to your plan amount. Unused credits from the previous month do not roll over. On-demand top-ups work differently: they remain available for 6 months and are only used once plan credits run out.",
    "home_faq_q5": "Does material reading consume credits?",
    "home_faq_r5": "Yes. Reading uses AI, so it carries a generation cost. But you pay once: every reading is saved in the Analyses tab and can be reused in future renders of that scene, in the plugin or browser.",
    "home_faq_q6": "What if I need more credits mid-month?",
    "home_faq_r6": "You can purchase a top-up at any time. Extra packages are in your account dashboard, apply instantly, and do not depend on your renewal date. They are only consumed after plan credits run out, and stay valid for 6 months.",
    "home_faq_q7": "How do the 7 free days work?",
    "home_faq_r7": "Create an account and get 7 days to explore the platform and use all local plugin tools that run on your computer: material reading and organization, Material ID, mirror and glass, model optimization, and purge. Image generation begins with a plan, which provides the credits. No credit card required for the trial.",
    "home_faq_q8": "Do I need to know how to write prompts?",
    "home_faq_r8": "No. Weak prompts are why AI makes mistakes, so that task is handled for you. Each Cora tool has an agent that writes technical prompts from your everyday description. Describe your project as you would to a colleague, and the technical side is handled automatically.",
    "home_faq_q9": "Can I use it on more than one computer?",
    "home_faq_r9": "Yes. On any plan, the web version supports up to 3 devices and the plugin up to 2 computers, one at a time. You can manage and remove devices from your account dashboard.",
    "home_faq_q10": "Does Cora include a material and component library?",
    "home_faq_r10": "No. It organizes and reads the libraries you already have: materials in .vrmat (V-Ray format) and components in .skp. If you already have a V-Ray library, point to the folder and keep working without converting anything.",
    "home_faq_q11": "Do I need an internet connection to work?",
    "home_faq_r11": "Yes. Account verification and AI processing happen in the cloud. With the plugin open, local modeling tools keep working even if your connection drops.",
    "home_faq_q12": "What if the image comes out wrong?",
    "home_faq_r12": "It happens. AI is probabilistic, and the same scene can yield different results. That is why the Edit tab exists: instead of rendering from scratch, fix only the affected area and preserve the rest of the image."
  },
  "es": {
    "home_link_precos_planos": "/es/precos#planos",
    "home_link_precos": "/es/precos",
    "home_hero_h1": "Del modelo 3D a la presentación final sin cambiar de programa.",
    "home_hero_apoio": "Cora lee los materiales y la luz de tu escena, en SketchUp o en el navegador. Revisas la lectura antes de generar, y la imagen sale fiel a lo que proyectaste.",
    "home_hero_btn_criar": "Crear cuenta",
    "home_hero_btn_planos": "Ver planes",
    "home_passos_titulo": "Todo el flujo en tres pasos:",
    "home_passos_q0_tipo": "Paso 1 · Captura",
    "home_passos_q0_desc": "Viewport de SketchUp encuadrada con el modelo 3D y el recorte exacto de proporción activo",
    "home_passos_q1_tipo": "Paso 2 · Lectura",
    "home_passos_q1_desc": "Interfaz de Cora mapeando geometría, materiales aplicados e iluminación de la escena antes de generar",
    "home_passos_q2_tipo": "Paso 3 · Render y Refinado",
    "home_passos_q2_desc": "Render finalizado con herramientas de cambio de clima, refinado de detalles y upscale en alta resolución",
    "home_passos_aria_lista": "Los tres pasos",
    "home_passos_tab0_titulo": "Modela y encuadra normalmente.",
    "home_passos_tab0_desc": "Continúa en SketchUp exactamente como lo haces. Cora marca en la viewport el encuadre exacto que entrará en la imagen, y guardas la escena.",
    "home_passos_tab1_titulo": "Cora lee la escena.",
    "home_passos_tab1_desc": "Antes de generar, la plataforma identifica los materiales y la luz que aplicaste en 3D. Revisas lo que mapeó, ajustas lo necesario y apruebas.",
    "home_passos_tab2_titulo": "Renderiza y refina en el mismo lugar.",
    "home_passos_tab2_desc": "La imagen nace fiel a la geometría. A partir de ahí editas detalles, cambias el clima, creas vistas 360° y amplías la resolución sin abrir otro programa.",
    "home_passos_nota_forte": "¿No usas SketchUp?",
    "home_passos_nota_texto": "En la versión web el paso 1 es subir una imagen. El resto es igual.",
    "home_demo_titulo": "De la captura al render, sin perder el proyecto.",
    "home_demo_p1_alt_depois": "La misma escena renderizada en Cora: sala y comedor con losa de concreto aparente, mesa de mármol verde, panel de madera y jardín de invierno tras el vidrio",
    "home_demo_p1_alt_antes": "La misma escena cruda en la viewport de SketchUp: geometría y encuadre idénticos, sin iluminación configurada y con materiales planos",
    "home_demo_p1_aria_alca": "Arrastra para comparar la captura de SketchUp con el render de Cora",
    "home_demo_p1_titulo": "El punto de partida",
    "home_demo_p1_desc": "La escena cruda de SketchUp, sin material tratado y sin luz. Arrastra para comparar con el render generado por Cora.",
    "home_demo_p2_aria_lista": "Cámaras del Batch",
    "home_demo_p2_cam1": "Cámara 01",
    "home_demo_p2_cam2": "Cámara 02",
    "home_demo_p2_cam3": "Cámara 03",
    "home_demo_p2_cam4": "Cámara 04",
    "home_demo_p2_cam5": "Cámara 05",
    "home_demo_p2_alt0": "Comedor y cocina en enfilade bajo el mismo techo alistonado, con banquetas en la barra y persona en circulación",
    "home_demo_p2_alt1": "Sala con pared de concreto aparente, sillón amarillo, cuadro colorido y jardín tropical tras el vidrio",
    "home_demo_p2_alt2": "Mesa de comedor con sillas verdes y lámpara de discos, escalera y cocina al fondo",
    "home_demo_p2_alt3": "Sala orientada al jardín tropical a través del vidrio, con televisor empotrado en la pared de concreto",
    "home_demo_p2_alt4": "Sala con panel de madera, televisor, dos sillones amarillos y escalera al fondo",
    "home_demo_p2_toque_ant": "Cámara anterior",
    "home_demo_p2_toque_prox": "Próxima cámara",
    "home_demo_p2_titulo": "Las cinco vistas",
    "home_demo_p2_desc": "Mismo ambiente, cinco cámaras. La madera, el piso y la luz siguen siendo los mismos en todas las imágenes.",
    "home_demo_p3_tipo": "Video Looping / GIF",
    "home_demo_p3_desc_rotulo": "Grabación de pantalla mostrando el cálculo del reflejo real del espejo en Cora Render",
    "home_demo_p3_titulo": "El espejo",
    "home_demo_p3_desc": "El reflejo muestra el ambiente que existe en el modelo, no uno inventado.",
    "home_demo_p4_alt_depois": "La misma planta humanizada por Cora: pisos con despiece real, mobiliario, vegetación y sombras calculadas por la luz solar",
    "home_demo_p4_alt_antes": "Plano técnico en líneas 2D exportado de CAD, mismo recorte y escala",
    "home_demo_p4_aria_alca": "Arrastra para comparar el plano técnico y el plano humanizado",
    "home_demo_p4_titulo": "El plano",
    "home_demo_p4_desc": "El dibujo técnico y el plano humanizado generado a partir de él.",
    "home_demo_p5_aria_visor": "Visor interactivo 360 grados. Arrastra con el ratón o toca para navegar por el ambiente.",
    "home_demo_p5_titulo": "El 360°",
    "home_demo_p5_desc": "Arrastra para recorrer el ambiente.",
    "home_ferramentas_titulo": "Una única línea de producción.",
    "home_ferramentas_apoio": "Cora lee la escena, genera, corrige y finaliza, en capas, hasta que la imagen esté lista para la presentación.",
    "home_ferramentas_aria_filtros": "Filtrar herramientas",
    "home_ferramentas_filtro_todas": "Todas",
    "home_ferramentas_filtro_imagem": "Imagen",
    "home_ferramentas_filtro_edicao": "Edición",
    "home_ferramentas_filtro_video": "Video",
    "home_onde_titulo": "En SketchUp o en el navegador",
    "home_onde_frase_1": "Misma cuenta, mismos créditos, mismo historial.",
    "home_onde_frase_2": "Lo que cambia es por dónde comienzas.",
    "home_onde_aria_switch": "Dónde usar Cora",
    "home_onde_tab_plugin": "Plugin para SketchUp",
    "home_onde_tab_web": "Versión web",
    "home_onde_plugin_titulo": "Plugin para SketchUp",
    "home_onde_plugin_p1": "Renderiza directo desde tu escena sin exportar archivos. El plugin reconoce la geometría y los materiales aplicados, captura el encuadre exacto de la viewport y calcula el reflejo real de los espejos del proyecto.",
    "home_onde_plugin_p2": "Incluye las herramientas locales para organizar materiales y componentes, proyectar texturas y optimizar el archivo en tu equipo, con procesamiento rápido y sin consumir créditos de la suscripción.",
    "home_onde_rotulo_plugin": "Plugin SketchUp",
    "home_onde_desc_plugin": "Captura de la interfaz del plugin Cora abierta en SketchUp con herramientas de materiales, viewport y reflejos",
    "home_onde_web_titulo": "Versión web",
    "home_onde_web_p1": "Diseñado para quienes modelan en Revit, Archicad y Promob, o parten de fotos de obra y bocetos conceptuales. Sube una imagen base para iniciar el render y la edición.",
    "home_onde_web_p2": "Accede al historial y refina imágenes desde cualquier computadora, tableta o teléfono por el navegador. El render 360° es la única herramienta exclusiva del plugin, al depender de la cámara 3D.",
    "home_onde_rotulo_web": "Versión Web",
    "home_onde_desc_web": "Captura de la interfaz de Cora en el navegador con subida de imagen (Revit, Archicad, Promob o boceto) y flujo de edición",
    "home_autoria_titulo": "Creado por quien ya hace esto cada día",
    "home_autoria_bio_1": "Marilia Fischer es arquitecta, trabaja en ArchViz hace 10 años y fundó 9barra7, estudio de renderizado que atiende constructoras y despachos de arquitectura.",
    "home_autoria_bio_2": "Cora Render nació de su flujo de trabajo, son herramientas que usa en el estudio y enseña en 9barra7 Academy.",
    "home_autoria_rotulo_alunos": "alumnos en 12 países",
    "home_autoria_alt_foto": "Marilia Fischer, arquitecta, fundadora de 9barra7 y creadora de Cora Render",
    "home_autoria_citacao": "“La IA no conoce a tu cliente, ni la intención del proyecto, ni qué decisiones de arquitectura son innegociables. Esa lectura sigue siendo tuya. Cora acelera el resto.”",
    "home_autoria_papel": "Arquitecta, fundadora de 9barra7 y creadora de Cora Render.",
    "home_planos_titulo": "Una suscripción única para todo el proceso de imagen.",
    "home_planos_apoio": "Del primer render al ajuste final de postproducción en alta resolución. Todas las etapas en una sola plataforma, dimensionada para el volumen de tu despacho.",
    "home_planos_pitch_starter": "Para comenzar.",
    "home_planos_por_mes": "/mes",
    "home_planos_creditos_mes": "créditos por mes",
    "home_planos_starter_aprox": "Aprox.",
    "home_planos_starter_img_em": "imágenes en",
    "home_planos_assinar_starter": "Suscribir Starter",
    "home_planos_selo_recomendado": "Recomendado",
    "home_planos_pitch_pro": "El día a día de quien entrega proyectos.",
    "home_planos_pro_beneficio": "Desbloquea animación, postproducción y upscale 16K",
    "home_planos_assinar_pro": "Suscribir Pro",
    "home_planos_pitch_studio": "Alto volumen.",
    "home_planos_studio_beneficio": "Fila de procesamiento prioritaria",
    "home_planos_assinar_studio": "Suscribir Studio",
    "home_planos_equipe_chamada": "¿Tienes dudas? Prueba 7 días en Free. ¿Es para todo el despacho? Conoce Cora Teams.",
    "home_planos_equipe_btn": "Ver planes y detalles",
    "home_faq_titulo": "FAQ",
    "home_faq_q1": "¿Necesito usar SketchUp?",
    "home_faq_r1": "No. El plugin es la puerta de entrada para quien modela en SketchUp, pero la versión web parte de cualquier imagen. Si trabajas en Revit, Archicad, 3ds Max, Promob o haces proyectos manuales, puedes subir tu archivo y comenzar por el navegador. Cuenta, créditos e historial son los mismos en ambas versiones.",
    "home_faq_q2": "¿Cora reemplaza a V-Ray o Enscape?",
    "home_faq_r2": "Sí, ese es el objetivo. Cora fue creado para no depender más de motores pesados y lentos. En lugar de pasar horas configurando luces físicas, mapas de materiales y esperando que el equipo responda, generas imágenes con calidad de presentación en minutos, directo desde tu archivo.",
    "home_faq_q3": "¿Qué son los créditos?",
    "home_faq_r3_parte1": "El crédito es la unidad que la IA consume en cada generación. Cada plan incluye una cuota mensual. Starter, por ejemplo, entrega",
    "home_faq_r3_parte2": "créditos, cerca de",
    "home_faq_r3_parte3": "imágenes en",
    "home_faq_r3_parte4": ". Las herramientas locales del plugin no usan IA y no consumen créditos.",
    "home_faq_q4": "¿Los créditos se acumulan de un mes a otro?",
    "home_faq_r4": "No. Cada mes tu cuota se renueva completa según tu plan. Lo que sobró del mes anterior no se suma a la nueva cuota. Las recargas independientes funcionan distinto: se guardan por 6 meses y solo se usan cuando se agotan los créditos del plan.",
    "home_faq_q5": "¿La lectura de materiales consume créditos?",
    "home_faq_r5": "Sí. La lectura usa IA, por lo que tiene costo de generación. Pero pagas una sola vez: cada lectura queda guardada en Análisis y se puede reutilizar en cualquier render futuro de esa escena, en el plugin o en el navegador.",
    "home_faq_q6": "¿Y si necesito más créditos a mitad de mes?",
    "home_faq_r6": "Puedes comprar una recarga en cualquier momento. Los paquetes adicionales están en el panel de tu cuenta, entran al instante y no dependen de tu fecha de renovación. Solo empiezan a consumirse cuando se terminan los créditos del plan, y duran 6 meses.",
    "home_faq_q7": "¿Cómo funcionan los 7 días gratis?",
    "home_faq_r7": "Creas tu cuenta y tienes 7 días para explorar la plataforma y usar todas las herramientas locales del plugin que funcionan en tu equipo: lectura y organización de materiales, Material ID, espejo y vidrio, optimizar modelo y purge. La generación de imágenes inicia con un plan, que incluye los créditos. En la prueba no pedimos tarjeta.",
    "home_faq_q8": "¿Necesito saber redactar prompts?",
    "home_faq_r8": "No. Un prompt mal planteado hace fallar a la IA, así que ese trabajo queda resuelto. Cada herramienta de Cora tiene un agente que escribe el prompt técnico a partir de tu descripción habitual. Describes la idea como lo harías con un colega, y el aspecto técnico queda resuelto.",
    "home_faq_q9": "¿Puedo usarlo en más de una computadora?",
    "home_faq_r9": "Sí. En cualquier plan, la versión web admite hasta 3 dispositivos y el plugin hasta 2 computadoras, con uso en una a la vez. Puedes administrar y quitar dispositivos desde el panel de tu cuenta.",
    "home_faq_q10": "¿Cora incluye biblioteca de materiales y componentes?",
    "home_faq_r10": "No. Organiza y lee las bibliotecas que ya tienes: materiales en .vrmat (formato de V-Ray) y componentes en .skp. Si ya tienes biblioteca de V-Ray, solo indicas la carpeta y sigues trabajando sin convertir nada.",
    "home_faq_q11": "¿Necesito internet para trabajar?",
    "home_faq_r11": "Sí. La validación de la cuenta y el procesamiento con IA suceden en la nube. Con el plugin abierto, las herramientas locales de modelado siguen funcionando aunque se interrumpa la conexión.",
    "home_faq_q12": "¿Y si la imagen sale con errores?",
    "home_faq_r12": "Puede suceder. La IA es probabilística, y la misma escena puede dar resultados distintos. Para eso existe la pestaña Editar: en lugar de renderizar todo de nuevo, corriges la zona afectada y conservas el resto de la imagen."
  }
};

export const MOTOR_TEXTOS = {
  "pt": {
    "ferramentas": [
      {
        "nome": "Render fotorrealista",
        "cat": "imagem",
        "txt": "Gera o render da geometria e dos materiais da cena, com luz calculada sem ajuste físico."
      },
      {
        "nome": "Batch, imagens em série",
        "cat": "imagem",
        "txt": "Aprovada a luz de um ângulo, o Cora repete a mesma leitura em todas as vistas."
      },
      {
        "nome": "Render 360°",
        "cat": "imagem",
        "txt": "Gera panoramas navegáveis direto da cena, para o cliente percorrer pelo navegador."
      },
      {
        "nome": "Planta baixa humanizada",
        "cat": "imagem",
        "txt": "Converte vistas de topo e linhas CAD em plantas com pisos reais e sombra calculada."
      },
      {
        "nome": "Mudar mood",
        "cat": "edicao",
        "txt": "Troca horário solar, clima e iluminação de uma imagem pronta, sem renderizar de novo."
      },
      {
        "nome": "Preenchimento e expansão",
        "cat": "edicao",
        "pro": true,
        "txt": "Troca objetos pontuais sem mexer na cena e expande a borda quando o corte apertou."
      },
      {
        "nome": "Pós-produção",
        "cat": "edicao",
        "pro": true,
        "txt": "Exposição, contraste, balanço de branco e curvas de tom, em camadas, na plataforma."
      },
      {
        "nome": "Upscale",
        "cat": "edicao",
        "txt": "Eleva a resolução para prancha executiva, telão e banner. Até 4x no Starter, 16K no Pro."
      },
      {
        "nome": "Animação",
        "cat": "video",
        "pro": true,
        "txt": "Transforma a perspectiva estática em vídeo em alta definição, com câmera guiada."
      },
      {
        "nome": "Timelapse de obra",
        "cat": "video",
        "pro": true,
        "txt": "Simula a evolução da obra ou a montagem do mobiliário a partir de uma imagem base."
      },
      {
        "nome": "Diretor de narrativa",
        "cat": "video",
        "pro": true,
        "txt": "Organiza os renders numa sequência cinematográfica e entrega o roteiro take a take."
      }
    ],
    "rot": {
      "imagem": "Imagem",
      "video": "Vídeo",
      "edicao": "Edição"
    },
    "passo_ant": "Passo anterior",
    "passo_prox": "Próximo passo",
    "voltar_ao_topo": "Voltar ao topo"
  },
  "en": {
    "ferramentas": [
      {
        "nome": "Photorealistic render",
        "cat": "imagem",
        "txt": "Renders scene geometry and materials with calculated light and no physical setup."
      },
      {
        "nome": "Batch, batch images",
        "cat": "imagem",
        "txt": "Once lighting is approved for one angle, Cora applies the same reading across all views."
      },
      {
        "nome": "360° render",
        "cat": "imagem",
        "txt": "Generates interactive panoramas directly from the scene for clients to tour in the browser."
      },
      {
        "nome": "Furnished floor plan",
        "cat": "imagem",
        "txt": "Converts top views and CAD linework into floor plans with real flooring and calculated shadows."
      },
      {
        "nome": "Change mood",
        "cat": "edicao",
        "txt": "Adjusts sun position, weather, and lighting on an existing image without re-rendering."
      },
      {
        "nome": "Generative fill and expand",
        "cat": "edicao",
        "pro": true,
        "txt": "Replaces specific items without altering the scene and expands borders when framing is tight."
      },
      {
        "nome": "Post-production",
        "cat": "edicao",
        "pro": true,
        "txt": "Exposure, contrast, white balance, and tone curves in layers, inside the platform."
      },
      {
        "nome": "Upscale",
        "cat": "edicao",
        "txt": "Boosts resolution for construction documents, presentations, and large prints. Up to 4x on Starter, 16K on Pro."
      },
      {
        "nome": "Animation",
        "cat": "video",
        "pro": true,
        "txt": "Turns static perspectives into high-definition video with guided camera paths."
      },
      {
        "nome": "Site timelapse",
        "cat": "video",
        "pro": true,
        "txt": "Simulates construction progress or furniture setup from a base image."
      },
      {
        "nome": "Narrative Director",
        "cat": "video",
        "pro": true,
        "txt": "Arranges renders into a cinematic sequence and provides a shot by shot script."
      }
    ],
    "rot": {
      "imagem": "Image",
      "video": "Video",
      "edicao": "Editing"
    },
    "passo_ant": "Previous step",
    "passo_prox": "Next step",
    "voltar_ao_topo": "Back to top"
  },
  "es": {
    "ferramentas": [
      {
        "nome": "Render fotorrealista",
        "cat": "imagem",
        "txt": "Genera el render de la geometría y materiales de la escena, con luz calculada sin ajuste físico."
      },
      {
        "nome": "Batch, imágenes en serie",
        "cat": "imagem",
        "txt": "Aprobada la luz de un ángulo, Cora repite la misma lectura en todas las vistas."
      },
      {
        "nome": "Render 360°",
        "cat": "imagem",
        "txt": "Genera panoramas navegables directo de la escena para que el cliente recorra en el navegador."
      },
      {
        "nome": "Plano humanizado",
        "cat": "imagem",
        "txt": "Convierte vistas de planta y líneas CAD en planos con pisos reales y sombra calculada."
      },
      {
        "nome": "Cambiar mood",
        "cat": "edicao",
        "txt": "Cambia posición solar, clima e iluminación de una imagen lista, sin renderizar de nuevo."
      },
      {
        "nome": "Relleno y expansión generativa",
        "cat": "edicao",
        "pro": true,
        "txt": "Reemplaza elementos puntuales sin alterar la escena y expande los bordes cuando el encuadre quedó ajustado."
      },
      {
        "nome": "Postproducción",
        "cat": "edicao",
        "pro": true,
        "txt": "Exposición, contraste, balance de blancos y curvas de tono, en capas, en la plataforma."
      },
      {
        "nome": "Upscale",
        "cat": "edicao",
        "txt": "Aumenta la resolución para láminas ejecutivas, pantallas y presentaciones. Hasta 4x en Starter, 16K en Pro."
      },
      {
        "nome": "Animación",
        "cat": "video",
        "pro": true,
        "txt": "Convierte perspectivas estáticas en video de alta definición con cámara guiada."
      },
      {
        "nome": "Timelapse de obra",
        "cat": "video",
        "pro": true,
        "txt": "Simula el avance de obra o el montaje del mobiliario a partir de una imagen base."
      },
      {
        "nome": "Director de Narrativa",
        "cat": "video",
        "pro": true,
        "txt": "Organiza los renders en una secuencia cinematográfica y entrega el guion toma a toma."
      }
    ],
    "rot": {
      "imagem": "Imagen",
      "video": "Video",
      "edicao": "Edición"
    },
    "passo_ant": "Paso anterior",
    "passo_prox": "Próximo paso",
    "voltar_ao_topo": "Volver arriba"
  }
};
